
package com.wang.ws;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CollectionWS", targetNamespace = "http://ws.wang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CollectionWS {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<com.wang.ws.RtnMethodResponse>
     */
    @WebMethod(operationName = "rtnMethod")
    @RequestWrapper(localName = "rtnMethod", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.RtnMethod")
    @ResponseWrapper(localName = "rtnMethodResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.RtnMethodResponse")
    public Response<RtnMethodResponse> rtnMethodAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "rtnMethod")
    @RequestWrapper(localName = "rtnMethod", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.RtnMethod")
    @ResponseWrapper(localName = "rtnMethodResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.RtnMethodResponse")
    public Future<?> rtnMethodAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RtnMethodResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rtnMethod", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.RtnMethod")
    @ResponseWrapper(localName = "rtnMethodResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.RtnMethodResponse")
    @Action(input = "http://ws.wang.com/CollectionWS/rtnMethodRequest", output = "http://ws.wang.com/CollectionWS/rtnMethodResponse")
    public List<String> rtnMethod();

}
