
package com.wang.ws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://ws.wang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.wang.ws.SayResponse>
     */
    @WebMethod(operationName = "say")
    @RequestWrapper(localName = "say", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.SayResponse")
    public Response<SayResponse> sayAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "say")
    @RequestWrapper(localName = "say", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.SayResponse")
    public Future<?> sayAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SayResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.SayResponse")
    @Action(input = "http://ws.wang.com/Hello/sayRequest", output = "http://ws.wang.com/Hello/sayResponse")
    public String say(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
