
package com.wang.ws;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JavaComplexType", targetNamespace = "http://ws.wang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JavaComplexType {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<com.wang.ws.GetPersonResponse>
     */
    @WebMethod(operationName = "getPerson")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.GetPersonResponse")
    public Response<GetPersonResponse> getPersonAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPerson")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.GetPersonResponse")
    public Future<?> getPersonAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPersonResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<com.wang.ws.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.GetPersonResponse")
    @Action(input = "http://ws.wang.com/JavaComplexType/getPersonRequest", output = "http://ws.wang.com/JavaComplexType/getPersonResponse")
    public List<Person> getPerson();

}
