
package com.wang.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JavaComplexTypeService", targetNamespace = "http://ws.wang.com/", wsdlLocation = "http://localhost:8080/JaxwsProject/w/JavaComplexTypeService?wsdl")
public class JavaComplexTypeService
    extends Service
{

    private final static URL JAVACOMPLEXTYPESERVICE_WSDL_LOCATION;
    private final static WebServiceException JAVACOMPLEXTYPESERVICE_EXCEPTION;
    private final static QName JAVACOMPLEXTYPESERVICE_QNAME = new QName("http://ws.wang.com/", "JavaComplexTypeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JaxwsProject/w/JavaComplexTypeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAVACOMPLEXTYPESERVICE_WSDL_LOCATION = url;
        JAVACOMPLEXTYPESERVICE_EXCEPTION = e;
    }

    public JavaComplexTypeService() {
        super(__getWsdlLocation(), JAVACOMPLEXTYPESERVICE_QNAME);
    }

    public JavaComplexTypeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAVACOMPLEXTYPESERVICE_QNAME, features);
    }

    public JavaComplexTypeService(URL wsdlLocation) {
        super(wsdlLocation, JAVACOMPLEXTYPESERVICE_QNAME);
    }

    public JavaComplexTypeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAVACOMPLEXTYPESERVICE_QNAME, features);
    }

    public JavaComplexTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JavaComplexTypeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JavaComplexType
     */
    @WebEndpoint(name = "JavaComplexTypePort")
    public JavaComplexType getJavaComplexTypePort() {
        return super.getPort(new QName("http://ws.wang.com/", "JavaComplexTypePort"), JavaComplexType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JavaComplexType
     */
    @WebEndpoint(name = "JavaComplexTypePort")
    public JavaComplexType getJavaComplexTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wang.com/", "JavaComplexTypePort"), JavaComplexType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAVACOMPLEXTYPESERVICE_EXCEPTION!= null) {
            throw JAVACOMPLEXTYPESERVICE_EXCEPTION;
        }
        return JAVACOMPLEXTYPESERVICE_WSDL_LOCATION;
    }

}
