
package com.wang.ws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTOMSimple", targetNamespace = "http://ws.wang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MTOMSimple {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.wang.ws.EchoDataResponse>
     */
    @WebMethod(operationName = "echoData")
    @RequestWrapper(localName = "echoData", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.EchoData")
    @ResponseWrapper(localName = "echoDataResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.EchoDataResponse")
    public Response<EchoDataResponse> echoDataAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "echoData")
    @RequestWrapper(localName = "echoData", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.EchoData")
    @ResponseWrapper(localName = "echoDataResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.EchoDataResponse")
    public Future<?> echoDataAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<EchoDataResponse> asyncHandler);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "echoData", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.EchoData")
    @ResponseWrapper(localName = "echoDataResponse", targetNamespace = "http://ws.wang.com/", className = "com.wang.ws.EchoDataResponse")
    @Action(input = "http://ws.wang.com/MTOMSimple/echoDataRequest", output = "http://ws.wang.com/MTOMSimple/echoDataResponse")
    public void echoData(
        @WebParam(name = "arg0", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<byte[]> arg0);

}
