
package com.wang.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTOMCustomer", targetNamespace = "http://ws.wang.com/")
public interface MTOMCustomer {


    /**
     * 
     * @param customer
     */
    @WebMethod
    @Action(input = "http://ws.wang.com/MTOMCustomer/uploadCustomerByNameRequest", output = "http://ws.wang.com/MTOMCustomer/uploadCustomerByNameResponse")
    public void uploadCustomerByName(
        @WebParam(name = "customer", partName = "customer")
        Customer customer);

}
